def substring(s, t, index):
    for j in range(len(t)):
        if s[index+j] != t[j]:
            return False
    return True

def dna_motif(s, t):  
    res = []
    for i in range(len(s) - len(t)):
        if substring(s, t, i):
            res.append(i+1)
    return res 

s = "CGGTACGTGGGTACGTAGGTACGTAGGTACGTGGTACGTGGAGGTCGGTACGTATTGGGGTACGTGGTACGTGGTACGTACGGTACGTGGGGTACGTGGTACGTGGTACGTTCAAGGTACGTCGGTACGTTTAGGTACGTGGTACGTCGTGGTACGTGGTACGTCCCGGTACGTGGTACGTAGGTACGTGTTGGTACGTCTAGGTACGTGGTACGTGTTGGTACGTATTGGTACGTTAGTCGGTACGTGGTACGTTATTCGAACTGGTACGTGTCGGTACGTGGGTACGTAGGTACGTGGTACGTTGGTACGTCGGTACGTCGGTACGTGGTACGTGCCAGGTACGTTGGTACGTGGTACGTGAGGGGTACGTGGGGTACGTCGTGGTACGTGGAATTGGTACGTGTCGGTACGTAATTTCGGGTACGTTTGGTACGTTGGTACGTGGGTACGTGGTACGTTGGTACGTACGGTACGTAGAGGTACGTAGTGGTACGTGCGGTACGTGGTACGTGGCGGTACGTTGGGTACGTAATAGGTACGTGAGAGTGGTACGTAGACTATCGGTACGTTACTATTCACCAGGTACGTGTTCGGTACGTGGTACGTAACCCACCTTTCTGATACCAGGGTACGTTCCGGTACGTAGTAGCCCGGTACGTGCTTTATACTATGGGTACGTATGTGGTACGTTGGTACGTCAGTCGAGGTACGTATGGTACGTGGGTACGTTTGCGGTACGTCCCAGGCAACTCAATTGGTACGTGGCGAGGGTACGTCAGGTACGTCAATCGGGTACGTAGTCAAGGTACGTTTAGGTACGTCTCGGAGGTACGTTAGGTACGTGGTACGTCGGTACGTGTCGGCCGGTACGTCAGGTACGTGGTACGTCTTGGTACGTATGGTACGTGGTACGTCGGTACGTGCGCAGGGTACGTGGCCGGGTACGTTCTGGTACGTCCACGCGGTACGT"
t = "GGTACGTGG"

result = ""
for x in dna_motif(s, t):
    result += str(x) + " "

print(result)
    